### ISSUE TITLE
Salt 2018.3.0 - IOLoop is already running

### ISSUE THREAD

**Issue by justin-sunayu** [wcannon/salt-check#22] opened 2018-04-18 17:47 UTC
Hey there! I am eager to get started testing saltcheck after your fantastic talk. I managed to get the latest dev branch of salt going on a test master but all I get when I run saltcheck is the following:

```
[root@sm ~]# salt 'sm' saltcheck.run_highstate_tests
sm:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1601, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/saltcheck.py", line 163, in run_highstate_tests
        scheck = SaltCheck()
      File "/usr/lib/python2.7/site-packages/salt/modules/saltcheck.py", line 279, in __init__
        self.salt_lc = salt.client.Caller()
      File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1949, in __init__
        self.sminion = salt.minion.SMinion(self.opts)
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 787, in __init__
        lambda: self.eval_master(self.opts, failed=True)
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 451, in run_sync
        self.start()
      File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
        super(ZMQIOLoop, self).start()
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 751, in start
        raise RuntimeError("IOLoop is already running")
    RuntimeError: IOLoop is already running
[root@sm ~]# salt --version
salt 2018.3.0-2388-g1c1e4a4 (Oxygen)
```

Do I need more patching to run/test saltcheck?

Thank you!

**Comment by wcannon** [comment] 2018-04-18 23:42
I haven't tested against 2018.3.* salt open yet.

I'll try it out and get back to you.

**Comment by justin-sunayu** [comment] 2018-04-18 23:55
Ok thanks! Let me know if I can help test anything.

**Comment by wcannon** [comment] 2018-04-18 23:57
Just finished a simple test.  Something in the 2018.3 release broke saltcheck.  I'll have to spend a little time to fix this tomorrow or on the weekend.

In the meantime, 2018.3 started shipping with a previous version of saltcheck, released as part of salt open.  To use it you could clear the minion cache(saltutil.clear_cache) and remove the custom saltcheck module in your _modules dir, followed by a sync_all (saltutil.sync_all) 

btw, thanks for letting me know that the module is broken.  :-)

**Comment by justin-sunayu** [comment] 2018-04-19 00:12
No problem! Can't wait to work with it. Do you know of a working version combination? Should it work with 2017.7.5?

**Comment by wcannon** [comment] 2018-04-19 00:41
I think it will work with 2017.7.5.  I know it worked with 2017.3.....

**Comment by mudfly** [comment] 2018-06-08 14:50
Hi @wcannon do you have any updates on this bug? I am really excited to start working with your awesome testing framework, but we have already upgraded to 2018.3 at my company. While testing on 2017.3 is an option in vagrant, I won't realistically be able to use this against existing hosts.

**Comment by wcannon** [comment] 2018-06-08 15:08
Hi,

I'm planning to fix and add upgrades to saltcheck in the next few weeks.

**Comment by justin-sunayu** [comment] 2018-06-08 15:11
If you need any help testing let us know! I am eager to start using this more!

**Comment by justin-sunayu** [comment] 2018-06-20 22:14
Still getting this in 2018.3.1

**Comment by wcannon** [comment] 2018-06-20 22:19
Yes.  Haven't made changes / fixes yet.  Setting up new dev / test
environment tomorrow.  So, hopefully will have some fixes in soon.

**Comment by wcannon** [comment] 2018-06-21 20:05
I just started testing this against 2018.3.1 and can't repeat the issue.  Note: I did just push a few small fixes as well - but not for the IO loop specifically.

Can you give me more info?  And, would you mind doing a pull and repeating the test?

I'm using a docker container based on ubuntu 16.04 + salt 2018.3 (pinning to major version)

Running single tests, state tests, and highstate tests now work.

**Comment by justin-sunayu** [comment] 2018-06-21 20:59
I'll try and recreating my environment in the next few days. I am running on Centos 7, maybe that is where the issue lies...

**Comment by justin-sunayu** [comment] 2018-06-21 21:43
I can confirm fresh installs of centos master/minion on 2018.3.1 produce the same issue. Is anyone else getting this on centos 7?

**Comment by wcannon** [comment] 2018-06-21 22:12
That is disappointing.  I'm going to set up a docker image and using
centos7 and try another test.

**Comment by wcannon** [comment] 2018-06-21 22:30
I just ran the state tests and highstate tests using only a salt-minion (eg
salt-call saltcheck.run_highstate_tests) and it worked.

It sounds like this must be a master/minion problem.

I'm downloading the centos7 dvd iso.  Will test early tomorrow.  Thanks for
running the test for me and letting me know the results.

**Comment by mudfly** [comment] 2018-06-22 01:02
I was using CentOS 7 (and maybe 6) in vagrant when I experienced this bug. it would be very easy for me to recreate and test. I am going on vacation for 2 weeks, but I may have time in the morning to run through this.

**Comment by wcannon** [comment] 2018-06-22 01:38
Thanks @mudfly 

I am able to reproduce the bug using CentOS7.  

The bug doesn't show up using salt-call.  Only when using salt as a master/minion scenario.

So, now I can work on the issue.  I suspect there were some code changes on salt open that I need to identify, and copy their solutions.

I'll likely handle this tomorrow morning.  I hope to get a solution checked in early tomorrow.

**Comment by justin-sunayu** [comment] 2018-06-22 02:05
Thanks so much for looking into this! I look forward to testing.

**Comment by wcannon** [comment] 2018-06-23 21:43
Update:  my assumption was that saltcheck (in salt open) was working in release 2018.3.  But, I just installed a fresh ubuntu 16.04 with salt 2018.3 and found that was not the case.

So...this looks like a more complicated fix than I thought it would be.  I had thought I could simply take the changes made in salt open and apply them to saltcheck and things would work......wrong!

Anyone who figures out this IOLoop tornado related message is my hero.

**Comment by wcannon** [comment] 2018-06-24 02:17
ok, this was bugging me.  So, after some additional sleuthing I believe I fixed the issue.  

However, additional testing is needed.  I've got this working on ubuntu 16.04 with salt 2018.3, with the master and minion on the same server.

I need to test this with separate master/minion and other versions of salt (e.g. 2017.7 and etc).

My main concern is the file_client='local' line, used as part of creating the salt.client.Caller() passing in mopts.

**Comment by justin-sunayu** [comment] 2018-06-24 02:20
I can help test. Can you give me a diff or branch to use for testing?

**Comment by wcannon** [comment] 2018-06-24 12:57
oops, I forgot to push to the repo last night.  Sorry!

I just tested ubuntu 16.04 with salt 2018.3 with the update using vagrant with separate servers for master and minion - success!

I'm going to close this now.  But, I will also set up vagrant to test 2017.7 for backward compatibility.

**Closed by wcannon** 2018-06-24 12:57 UTC

**Comment by justin-sunayu** [comment] 2018-06-25 00:10
Confirmed this works for me now on 2018.3.1 Centos7! Thanks
